Animated webp support
livingbio/ffmpeg-media-type pull request #39
Opened 2023-11-09 09:57 UTC by Touyu-Pan

## Context

let ffprobe support animated webp image

ref: https://github.com/livingbio/gstudio/issues/13253

## Summary

- 新增 decorator `animated_webp_support`
如果 webp 不是 VP8 chunk, 會先用 `webpmux` 截取一個 frame, 並用於製作 thumbnail

## Relevant Technical Choices

## To-do

確認 `get_webpmux` 關於 docker 的部分怎麼寫

## User-facing changes

## Testing Instructions

https://github.com/livingbio/ffmpeg-media-type/assets/54736761/05a995a6-fbaa-4907-ac75-b73946eddbb1

## Checklist

- [x] I have tested this code
- [x] I have added documentation where necessary

2023-11-09 10:29 UTC, lucemia commented
要寫 test case
 Ffmpeg 要取 docker 是因為不同版本支援度有差異

Webp 的部分可以直接 call 就好

2023-11-09 13:19 UTC, lucemia commented on src/ffmpeg_media_type/utils/ffmpeg.py
> +            webpmux_command = ["webpmux", "-get", "frame", "1", uri, "-o", uri]
uri 有可能是 URL 
確定可以用作 webmux 的 input and output 嗎?

2023-11-09 13:21 UTC, lucemia commented on src/ffmpeg_media_type/utils/ffmpeg.py
> +            webpmux_command = ["webpmux", "-get", "frame", "1", uri, "-o", uri]
另外 animate webp 作為 input 時不是 ffprobe 會直接掛掉嗎?  為什麼這裡的邏輯是先跑 ffprobe, 再做 webmux 的處理? 目前用在 test case 的 webp 確定是 animate webp 嗎?

2023-11-10 03:20 UTC, Touyu-Pan commented on src/ffmpeg_media_type/utils/ffmpeg.py
> +            webpmux_command = ["webpmux", "-get", "frame", "1", uri, "-o", uri]
> uri 有可能是 URL 確定可以用作 webmux 的 input and output 嗎?

如果是 url 的話不行
我看 [sdk.media.info.extract](https://github.com/livingbio/gstudio/blob/07042f0a94c0c57795ee0335a84ee96b17d92fb9/src/sdk/media/info.py#L12-L16) 會先 download 再 detect, 不過這確實不能涵蓋全部的 case
會再修改, 謝謝

> 另外 animate webp 作為 input 時不是 ffprobe 會直接掛掉嗎? 為什麼這裡的邏輯是先跑 ffprobe, 再做 webmux 的處理?

ffprobe 還不會掛掉
會掛掉的是 detect 到 generate_thumbnail 的時候
雖然不會掛掉，但 ffprobe 出來的資料會沒有長跟寬

https://github.com/livingbio/ffmpeg-media-type/assets/54736761/1c2b4a8a-0372-4b22-8ccf-6d0d51435b57

> 目前用在 test case 的 webp 確定是 animate webp 嗎?

確定是
testing instruction 中我用同樣的 input,
一開始是用原本的 code, 有重現錯誤
再以相同的 input, 以及修改後的 code 再跑一次, 沒有報錯

2023-11-10 10:24 UTC, Touyu-Pan commented on src/ffmpeg_media_type/utils/tests/__snapshots__/6.0/test_ffmpeg.ambr
> +      'format_long_name': 'QuickTime / MOV',
<img width="1510" alt="image" src="https://github.com/livingbio/ffmpeg-media-type/assets/54736761/3d0c75f5-da61-4d9a-8f75-6bdf889e653a">

我的 ffmpeg 也是 6.0
為什麼我更新的 snapshot 資訊會比較多 🤔

2023-11-10 10:48 UTC, lucemia commented
如果確定沒錯的話 可以先照 CEO 結果 手動修 snapshot

2023-11-10 11:21 UTC, Touyu-Pan commented
### url as input_url ( "https://storage.googleapis.com/livingbio-tmp/lionic_vp8x_1109.webp" )

<img width="1509" alt="image" src="https://github.com/livingbio/ffmpeg-media-type/assets/54736761/9edc600c-61bd-44d1-a7e6-be3762399a10">

### local path as input_url

<img width="1512" alt="image" src="https://github.com/livingbio/ffmpeg-media-type/assets/54736761/ec67c36b-7427-41b3-9b85-3e906bc165de">

2023-11-10 11:29 UTC, lucemia commented
我好像有個地方有檢查我有沒有安裝 ffmpeg 
如果有的話 也補上檢查 webpmux 的功能

2023-11-13 05:20 UTC, Touyu-Pan commented
> 我好像有個地方有檢查我有沒有安裝 ffmpeg

如果我沒看錯的話 是用 `-version` 來檢查的對嗎 ?

> 如果有的話 也補上檢查 webpmux 的功能

我補在用到 webpmux 的 cmd 之前

2023-11-13 11:40 UTC, lucemia commented
> > 我好像有個地方有檢查我有沒有安裝 ffmpeg
> 
> 如果我沒看錯的話 是用 `-version` 來檢查的對嗎 ?
> 
> > 如果有的話 也補上檢查 webpmux 的功能
> 
> 我補在用到 webpmux 的 cmd 之前

這樣子會變成每次使用都要重新呼叫一次，
比較正確的做法是做在

`ffmpeg_media_type/__init__.py` 裡面，檢查一次就好
由於 ffmpeg 的檢查也還沒有做，這個 PR 可以先將 webpmux 的檢查也拿到，到時候一起補

2023-11-14 02:24 UTC, lucemia requested changes

2023-11-14 02:24 UTC, lucemia commented on src/ffmpeg_media_type/utils/ffmpeg.py
> +                return func(f.name)
`call(webpmux_command)` 的部分不必要的重複了

```
if uri.startswith("http")
  檔案下載

對下載好的檔案做處理

```

2023-11-14 02:24 UTC, lucemia commented on src/ffmpeg_media_type/utils/ffmpeg.py
> +            _, file_ext = os.path.splitext(file)
url 中的 path 不保證能夠取得合法的檔案名稱 & ext

這裡應該用 NamedTemporaryFile 然後副檔名給 "webp" 就好

2023-11-14 03:04 UTC, lucemia commented
@Touyu-Pan 謝謝

最後確認一下這個新的 webp case 有在這裡測試到

https://github.com/livingbio/ffmpeg-media-type/blob/main/src/ffmpeg_media_type/tests/test_info.py

2023-11-14 03:25 UTC, lucemia approved these changes

2023-11-14 03:29 UTC, merged